.Dd $Mdocdate$
.Dt ISPRIME 1
.Os
.Sh NAME
.Nm isprime
.Nd checks if number is a prime number
.Sh SYNOPSIS
.Nm isprime
.Op Fl v
.Op Fl n
.Op Fl b
.Op Ar number
.Sh DESCRIPTION
The
.Nm
utility checks if a number is prime.  
.Pp
If the number is prime it returns the number, or the first divisor if not prime.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl v
Verbose - gives verbose output. If the number is not prime it returns the previous prime and the next prime numbers.
.It Fl n
Nearest - gives the prime number nearest to the number given.
.It Fl b
Boolean - returns 0 for false or 1 for true, if used with the 
.Op Fl v 
it will return 'True' or 'False'
.El
.Pp
If the number given is prime then the 
.Op Fl v
and 
.Op Fl n
have no effect.
.Sh HISTORY
.Nm 
was initially written to check if a year was a prime number.
.Sh SEE ALSO
.Lk http://www.xkcd.com/1779/ 
.Sh AUTHORS
.An Fred Crowson Aq Mt fcbsd@crowsons.com
